"""days_to_hire_table

Revision ID: 32d1567c2657
Revises: 991ecb2bf269
Create Date: 2025-07-07 22:19:10.290264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32d1567c2657'
down_revision = '991ecb2bf269'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('days_to_hire',
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('standard_job_id', sa.String(), nullable=False),
    sa.Column('average', sa.Integer(), nullable=False),
    sa.Column('minimum', sa.Integer(), nullable=False),
    sa.Column('maximum', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('country_code', 'standard_job_id'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('days_to_hire', schema='public')
    # ### end Alembic commands ###
