"""change_days_to_hire_columns_to_numeric

Revision ID: 41ce1b0300ae
Revises: 32d1567c2657
Create Date: 2025-07-08 16:09:11.675552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41ce1b0300ae'
down_revision = '32d1567c2657'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('days_to_hire', 'average',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=5, scale=1),
               existing_nullable=False)
    op.alter_column('days_to_hire', 'minimum',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=5, scale=1),
               existing_nullable=False)
    op.alter_column('days_to_hire', 'maximum',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=5, scale=1),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('days_to_hire', 'maximum',
               existing_type=sa.Numeric(precision=5, scale=1),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('days_to_hire', 'minimum',
               existing_type=sa.Numeric(precision=5, scale=1),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('days_to_hire', 'average',
               existing_type=sa.Numeric(precision=5, scale=1),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
